### ISSUE TITLE
SARIMA doesn't run for stock data

### ISSUE THREAD

**Issue by swhustla** [swhustla/comparison_of_time_series_methods#48]

**Comment by swhustla** [comment]
@karukes what is the error you get - does it just freeze? Thanks.

**Comment by swhustla** [comment]
It seems to simply run very very slowly: https://datascience.stackexchange.com/questions/90327/python-sarimax-model-fits-too-slow

Here's the output
```Machine precision = 2.220D-16
 N =            2     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  5.73619D+00    |proj g|=  2.01146D+00

At iterate    5    f=  4.87012D+00    |proj g|=  5.68611D-03

At iterate   10    f=  4.84592D+00    |proj g|=  1.86327D-01

...```

**Comment by karukes** [comment]
I have waited like 3h for SARIMA to start running but it does not move further this line "Predicting Stock price, specifically JPM using SARIMA..."

**Comment by swhustla** [comment]
Notes. I am switching over to a different library :)
