### ISSUE TITLE
Problem in comparison_plot.py with axis.fill_between()

### ISSUE THREAD

**Issue by karukes** [swhustla/comparison_of_time_series_methods#70]
if axis.fill_between() is commented --> no further errors
<img width="1040" alt="Screenshot 2022-12-19 at 09 57 51" src="https://user-images.githubusercontent.com/25456766/208386994-f9319c18-0015-4428-8116-8f9e0c12a574.png">

**Comment by swhustla** [comment]
@karukes which method and dataset was this with? Thanks
