### ISSUE TITLE
Prophet doesn't run for Sun spots data 

### ISSUE THREAD

**Issue by karukes** [swhustla/comparison_of_time_series_methods#75]
This bug has been discussed here:
https://stackoverflow.com/questions/58069787/facebook-prophet-overflow-error-when-fitting

<img width="1193" alt="Screenshot 2022-12-20 at 21 03 04" src="https://user-images.githubusercontent.com/25456766/208756453-833fc5c6-1099-49ab-9391-38d215f069df.png">

**Comment by karukes** [comment]
If I limit the data to the range from 1720 to 2009 it works (below 1720 it gives the overflow error). Looks like there's no a better solution?

**Comment by swhustla** [comment]
@karukes what is the significance of 1720?

**Comment by karukes** [comment]
@swhustla the data for Sun spots start from 1700 year, so instead if one starts from 1720 year then the method runs

**Comment by swhustla** [comment]
I see. The error occurs with this line: ```forecast_in_sample_plus_future = model.predict(future_in_sample)```

**Comment by swhustla** [comment]
It looks like an issue because the time span is too long for Numpy: https://stackoverflow.com/questions/56720783/how-to-fix-overflowerror-overflow-in-int64-addition. Hence your 1720 fix may be the only option.
